### ISSUE TITLE
Fish atlas name

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainatlas-api#12]
https://github.com/brainglobe/brainatlas-api/blob/db8fa4f303f52a29e68cf330e8eac58b35624bee/brainatlas_api/bg_atlas.py#L88

Hey @vigji I don't know if there's other fish atlases out there, but should we change this zebrafish?

**Comment by adamltyson** [comment]
I think we should move towards more specific names generally. There might be a bright future of many many zfish atlases.

**Comment by vigji** [comment]
Yup, we should definitively find some consistency. I was calling it fish atlas b/c that's what they call it. Any Ideas? Should we keep to some extent names that are out there as it's what people would get? Or just move to entirely systematic names?

**Comment by adamltyson** [comment]
Maybe `lab/author/institute_species_additional-info_resolution_version`?

This would give e.g.:
* `allen_mouse_CCFV3_10um_0.0`
* `swanson_rat_waxholm_125um_0.0`

**Comment by vigji** [comment]
I like it! This should be the name in the "name" metadata entry, the compressed file filename, and the uncompressed folder.

For the related classes we could just abbreviate to the first 2 plus maybe resolution + `Atlas` only if ambiguous? `AllenMouse10umAtlas` and `SwansonRatAtlas`?

**Comment by adamltyson** [comment]
Yeah we can abbreviate. I was thinking we could keep resolution, because I would like to support additional resolutions (via downsampling) of atlases. e.g. [this atlas](https://www.nature.com/articles/s41467-019-13057-w) is only provided at one resolution, but it's in ARA space, so I'm going to make 10um, 25um, 50um & 100um versions of it.

**Comment by vigji** [comment]
Wow, so many atlases I am not aware of! :D 

Sure, but maybe we can have resolution only when we explicitly want to support multiple ones and leave for other atlases the cleaner name?

**Comment by adamltyson** [comment]
I'd prefer specifying the resolution now. I did this exact thing with amap, and now some people have a confusing mix of `allen_2017` and `allen_2017_10um` when I later decided to support multiple resolutions.

**Comment by vigji** [comment]
But I mean for the classes names - for the atlases names that should always be mandatory!

**Comment by FedeClaudi** [comment]
agree with all above :)

**Comment by adamltyson** [comment]
> But I mean for the classes names - for the atlases names that should always be mandatory!

Ahh yes, sorry. Fully descriptive names for the atlases, and then shorter, unique names for the classes?

**Comment by vigji** [comment]
I mean, shorter and unique but not arbitrary - following your naming system, I would say

AuthorSpecies[Additionalinfo][00um]

With optional additional info and resolution.

**Comment by adamltyson** [comment]
Sounds good

**Comment by FedeClaudi** [comment]
Sounds like we have found an agreement, will close for now
