### ISSUE TITLE
Introducing dataclasses?

### ISSUE THREAD

**Issue by vigji** [brainglobe/brainatlas-api#25]
I think that [dataclasses](https://docs.python.org/3/library/dataclasses.html) would be very convenient to clean up the controls on the metadata structure and potentially in other places.
Downside is, they were introduced in `python 3.7`. I never tried to support them on python 3.6 but [it should be pip installable there](https://pypi.org/project/dataclasses/)

**Comment by adamltyson** [comment]
I haven't used them, but from my point of view, I'm ok if we need to drop Python 3.6 support. Might not be ideal for brainrender though.

**Comment by FedeClaudi** [comment]
I think brainrender works with 3.7

**Comment by adamltyson** [comment]
> I think brainrender works with 3.7

It does, but unlike amap/cellfinder in which users are likely to have a dedicated python environment, brainrender users are more likely to use it with other packages (which may require other python versions).

**Comment by FedeClaudi** [comment]
yeah fair point. 
What's the advantage of dataclasses? Other than that they fill in __init__ automatically

**Comment by vigji** [comment]
It's a neat concise way to ensure data type consistency (plus little nice json i/o maybe) that can be handy for metadata description. Is not revolutionary though, and looking more into it it does not provide tools to do easily other validations apart from type. So probably can be left out for the moment!
