### ISSUE TITLE
Specifying atlas orientation

### ISSUE THREAD

**Issue by vigji** [brainglobe/brainatlas-api#26]
I am trying to figure out a convenient way of describing the orientation of the atlas being imported so that the stack reorientation and affine matrix generation can be handled in a function.

Do you think that something like this would make sense? Specifying the "sectioning" of the atlas, although maybe more intuitive, is prone to lots of ambiguities as each cut can be oriented in two ways. Therefore, one should specify axes names order and axes directions. Is this intuitive enough/adhering to conventions in people's mind?

```
# Describe the order and direction the atlas axes; tuple specifies (0, 0, 0) for each of the stack axes:
atlas_origin = ("posterior", "superior", "right")
```

**Comment by adamltyson** [comment]
This was never fully sorted for amap, [we defined the sectioning (saggital, coronal etc), and then also whether any of the axis directions were different from the nifti convention. 
](https://docs.cellfinder.info/amap/getting-started/image-orientation)
I think your proposal is equivalent, but a bit neater.

> atlas_origin = ("posterior", "superior", "right")

Would this deal with rotations? Sometimes people's data isn't acquired in the "normal" anatomical orientation so that it can fit in a microscope etc.

**Comment by vigji** [comment]
If you mean 90 deg rotations yes, they can just be described with the origin tuple; if you mean non - 90 deg rotations (like, a diagonal midline), no, that cannot be handled without a full affine transformation which I would like to keep out of this "space convention" definition and transformation.

The class I am ending up writing is a bit abstract but hopefully very useful to convert easily stuff from one anatomical space to the other defining the space just with the origin tuple, which is a general problem that I never handled properly. I think I'll make a complete little package - maybe `bgspace` - out of it.

**Comment by adamltyson** [comment]
> If you mean 90 deg rotations yes, they can just be described with the origin tuple; if you mean non - 90 deg rotations (like, a diagonal midline), no, that cannot be handled without a full affine transformation which I would like to keep out of this "space convention" definition and transformation.

Sounds great. I agree that 90 degree rotations should be handled by the atlas api (or another tool), but anything weirder is up to the user to preprocess.

**Comment by vigji** [comment]
Ok, this has been sorted! I tried to make decent docs for `BGSpace`:

https://github.com/brainglobe/bgspace

I will start refactoring the fish atlas using this and see how it goes.

**Comment by vigji** [comment]
This should have been resolved with BGSpace for now
