### ISSUE TITLE
Speedup testing

### ISSUE THREAD

**Issue by vigji** [brainglobe/brainatlas-api#28]
Since we should be testing only the main API, that hopefully should be pretty contained in terms of dependencies/weird OSs interactions we can maybe restrict testing to Linux and to streamline it a bit also in the setup? We can always add back other OSs later when we reach a more stable version of things

**Comment by adamltyson** [comment]
We’re testing all the python versions and OSs in parallel, so would we save any time by removing them?

If we can, I’m keen to keep all the tests, to make sure I don’t use any Linux specific functions etc (which I’ve done before).

**Comment by vigji** [comment]
Last time I check they were not all running parallel, maybe there’s more than the limit of cores (I think that 6 are running parallel but we have eight- maybe we can test only on one python cross platform).

Also, avoiding installing all dev pag ages and installing explicitly shan’t needed (I guess black and flake8?) would improve it I think

**Comment by FedeClaudi** [comment]
yeah we can test just one python version for now.

**Comment by vigji** [comment]
This should be fixed in #29 now
