### ISSUE TITLE
Location of atlas folder and config file

### ISSUE THREAD

**Issue by vigji** [brainglobe/brainatlas-api#37]
This was raised and discussed a bit in #3, addressing it again if we want to aim for a first working release.
We need a way of specifying for brainglobe where is the default location if the atlases. Ideally, it should be easy to fix/change by the user. In the future we might want to support atlases in multiple locations but at the moment we will stick to a single folder, so it just need to contain a single path.

The options would be:
1. The current option: a variable in the package
2. A variable read from a config (.json?) file.

I think that in #3 we converged on the second option, in which case we need to decide where to keep this file. Again there are two alternatives:
i. In the brainglobe package directory;
ii. In the root directory.

The first option has the disadvantage of being messy to find to modify manually; the second might not be accessible e.g. on clusters, as I think @adamltyson was pointing out (I have no experience on clusters). I think that we can opt for i, but it would be nice if there was a way of changing it that does not require the user to browse all the way inside the package and modify the file manually, but a little utility (maybe prompt command?) like `brainatlas_api configure --atlas_path location` that checks if the new path is valid and updates the file. Would this be ok? Is the prompt command an overkill?

**Comment by FedeClaudi** [comment]
Why not a settings.json saved in the package directory + command line interface to override the default settings + programmatic access.
By programmatic access I mean somethink like an argument to `core.Atlas` or something like that. Since brainglobe-api will mostly be used to support other packages it would be useful to have something like that in place.

**Comment by vigji** [comment]
> Why not a settings.json saved in the package directory + command line interface to override the default settings + programmatic access.
> By programmatic access I mean somethink like an argument to `core.Atlas` or something like that. Since brainglobe-api will mostly be used to support other packages it would be useful to have something like that in place.

Of course, that specification is Already supported and I would maintain it!

**Comment by adamltyson** [comment]
> Why not a settings.json saved in the package directory + command line interface to override the default settings + programmatic access.

Definitely in favor of this.  Might be a bit more work on our side, but off the top of my head, I can't think of a way that this goes wrong. The possible issue is if the user doesn't have write access to their installation directory, but in that case they're unlikely to be changing anything themselves.

**Comment by vigji** [comment]
Addressed in #38
