### ISSUE TITLE
List available and downloadable atlases

### ISSUE THREAD

**Issue by vigji** [brainglobe/brainatlas-api#39]
I move this bit of the conversation out of the GIU discussion.

I agree it would definitively be a good thing to have. Happy if you @FedeClaudi can have a look into it, I will merge the config changes as soon as possible so that you can start from there given that it will strongly interact with these parts of the code.

I guess just a little function like `brainglobe_api.list_atlases()` that prints all the local atlases and their directory, and all the remote one. 

This raise two points that we can discuss in this context:
 - currently, keeping the "version" value at the level of the BGAtlas class is quite useless. Maybe there should vbe a global minimal (major) version requirement on the atlas for the brainatlas_api, so that only atlases with at least that major number are listed as available;
 - should we figure out a way of "proofreading" the atlases, maybe in some sort of CI-like fashon? I remember @adamltyson raised the problem of space considerations on Travis testing, I don't know the boundaries there.

**Comment by adamltyson** [comment]
As long as they work across OSs, I love all this stuff.

**Comment by vigji** [comment]
Sounds like a light dependency, why not! We could maybe use it for the atlas __repr__ as well?

**Comment by FedeClaudi** [comment]
> I guess just a little function like brainglobe_api.list_atlases() that prints all the local atlases and their directory, **and all the remote one**.

This part **and all the remote one** is something I might need with, I couldn't find any API for accessing an org's content on GIN, so not sure what the best way to get a list of available atlases is. Especially if we have some in `Atlases` and some in individual folders [though I think eventually we want each atlas in it's own folder?]: https://gin.g-node.org/brainglobe

I could make a web scraper or something like that to get a list of all atlas repos on the org's page but it's not a very clean solution, do you know of a better one? Given that we will only host a handful of atlases I am also not opposed to having a manually curated list/metadata file saved somewhere

**Comment by FedeClaudi** [comment]
I realised I was being daft, I could just use the classes in bgatlas, will send a PR soon

**Comment by FedeClaudi** [comment]
see: https://github.com/brainglobe/brainatlas-api/pull/40#issue-434783798
