### ISSUE TITLE
Visible or hidden folder?

### ISSUE THREAD

**Issue by vigji** [brainglobe/brainatlas-api#42]
We are currently using a hidden folder `.brainglobe` for storing the atlases. This matches the behavior of several packages that need to store their private information, but in our case the user might want to browse the files and also as it's quite large in memory would need to be accessible.

@adamltyson you were using the hidden path for cellfinder; do you have arguments in favour of hidden folder? Otherwise I would just make it visible.

**Comment by adamltyson** [comment]
I think I’m in favour of keeping the files hidden, and providing tools to allow users to inspect the atlases. 

My issue with making them visible is that it could be very easy for an inexperienced user to accidentally edit a json file, rendering the whole atlas unusable. 

My feeling is that users who know enough to explore a hidden directory, know enough to not play with them.

**Comment by FedeClaudi** [comment]
and if they want to save to a non-hidden folder they can do so with the tools provided

**Comment by vigji** [comment]
> My issue with making them visible is that it could be very easy for an inexperienced user to accidentally edit a json file, rendering the whole atlas unusable.

Ok, this sounds like a good point! I was raising it just because I was trying to load an atlas from the bgviewer and the hidden folder was not shown by the pyqt5 file dialog window. But I guess that eventually this should be handled with a dropdown manu using Fede new atlas listing functionalities?

**Comment by adamltyson** [comment]
>  I was raising it just because I was trying to load an atlas from the bgviewer and the hidden folder was not shown by the pyqt5 file dialog window

I think you can change this, according to [this post](https://www.qtcentre.org/threads/67923-Get-QFileDialog-to-display-dot-folder-files):
```python
fdlg = QtWidgets.QFileDialog()
        fdlg.setFilter(QDir.AllEntries | QDir.Hidden)
        if (fdlg.exec()):
            fileNames = fdlg.selectedFiles()
        fdlg.close()
```

> But I guess that eventually this should be handled with a dropdown manu using Fede new atlas listing functionalities

I think this is the way forward.
