### ISSUE TITLE
Atlas.root

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainatlas-api#6]
Hey @vigji  I'm getting up to speed with all the great work you've done recently. I have one small question comment about this:

https://github.com/brainglobe/brainatlas-api/blob/54b37bed32b12265a7d66aabb68d0dcaea2035bb/brainatlas_api/core.py#L52

Given that `root` is used in some atlases (e.g. Allen) to refer to the lowest hierarchy structure (i.e. the whole brain),  won't the use of `self.root` to refer to the base path cause confusion?

e.g. here:
https://github.com/brainglobe/brainatlas-api/blob/54b37bed32b12265a7d66aabb68d0dcaea2035bb/brainatlas_api/core.py#L116

I know that `self.root` is mostly internal and users won't be using it but maybe we can give it a different name?

**Comment by vigji** [comment]
Makes perfect sense! I will change it to `root_dir`.

**Comment by FedeClaudi** [comment]
thanks
