### ISSUE TITLE
moving structures/brainatlas-api

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainatlas-api#7]
Hey @vigji , 

Is there any reason why you have for instance `structures/brainatlas_api/simple_tree.py` instead of having it under `brainatlas_api/structures` ? 

I think that having all code under `brainatlas_api/..` will make it easier to package the whole thing into a pip-installable package, though surely @adamltyson  knows better about this. Either way it might be good to keep all code in the same place.

By the way thanks for all the work you've done so far, Adam and I will get started with the Rat atlas soon. It looks like it's all coming together rather nicely!

**Comment by vigji** [comment]
My PyCharm did some weird automatic refactoring, I should have fixed that in the last push!

That's great to hear, I have an almost complete version of the fish one! 
Now to learn a bit the `BrainRender` structure I am trying to make a there a class that supports the `BrainRender` scene creation and editing using a brainglobe atlas, will make a PR by this evening I hope! :)

**Comment by vigji** [comment]
Yes! While doing it I am also copying empty methods in the brainglobe Atlas, as several of those would be good to have in the general class as they are useful in many places.

**Comment by FedeClaudi** [comment]
yeah, would be good to move as much as possible to brainglobe atlas. Once brainglobe is fully functional I will refactor brainrender to rely more on it obviously. Ideally replacing most of the base atlas class.
